# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

import_from_git(
  url: "git@github.com:foxsofter/fastlane_pod_template.git", # The URL of the repository to import the Fastfile from.
  branch: "master", # The branch to checkout on the repository. Defaults to `HEAD`.
  path: "fastlane/Fastfile" # The path of the Fastfile in the repository. Defaults to `fastlane/Fastfile`.
)
lane :release do |options|
  pod_name = options[:pod_name]
  release_pod(pod_name: pod_name)
end